function [A_cart,B_cart,C_cart] = cart_pendulum_system(in1)
%CART_PENDULUM_SYSTEM
%    [A_cart,B_cart,C_cart] = CART_PENDULUM_SYSTEM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/30 13:08:30

Iw = in1(6,:);
Jp = in1(8,:);
M = in1(1,:);
btheta = in1(10,:);
bx = in1(9,:);
g = in1(3,:);
l = in1(4,:);
m = in1(2,:);
r = in1(5,:);
t2 = Iw.*2.0;
t3 = l.^2;
t4 = r.^2;
t5 = Jp.*t2;
t6 = M.*t4;
t7 = m.*t3;
t8 = m.*t4;
t9 = Jp.*t6;
t10 = Jp.*t8;
t11 = Jp+t7;
t12 = t2.*t7;
t13 = t6.*t7;
t14 = t2+t6+t8;
t15 = t5+t9+t10+t12+t13;
t16 = 1.0./t15;
A_cart = reshape([0.0,0.0,0.0,0.0,1.0,-bx.*t4.*t11.*t16,0.0,bx.*l.*t8.*t16,0.0,-g.*t7.*t8.*t16,0.0,g.*l.*m.*t14.*t16,0.0,btheta.*l.*t8.*t16,1.0,-btheta.*t14.*t16],[4,4]);
if nargout > 1
    B_cart = [0.0;t4.*t11.*t16;0.0;-l.*t8.*t16];
end
if nargout > 2
    C_cart = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0],[2,4]);
end
end
