function [A_motor,B_motor,C_motor,E_motor] = dc_motor_system(in1)
%DC_MOTOR_SYSTEM
%    [A_motor,B_motor,C_motor,E_motor] = DC_MOTOR_SYSTEM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/30 13:08:30

G = in1(7,:);
Ke = in1(12,:);
Kt = in1(11,:);
La = in1(14,:);
Ra = in1(13,:);
r = in1(5,:);
t2 = 1.0./La;
A_motor = -Ra.*t2;
if nargout > 1
    B_motor = t2;
end
if nargout > 2
    t3 = 1.0./r;
    C_motor = G.*Kt.*t3.*2.0;
end
if nargout > 3
    E_motor = -G.*Ke.*t2.*t3;
end
end
