function B = linear_B_matrix(in1)
%linear_B_matrix
%    B = linear_B_matrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/27 10:08:34

%2モータ対称制御の線形化B行列
La = in1(14,:);
B = [0.0;0.0;0.0;0.0;1.0./La];
end
