function B = linear_B_matrix(in1)
%linear_B_matrix
%    B = linear_B_matrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/23 13:04:31

La = in1(15,:);
B = [0.0;0.0;0.0;0.0;1.0./La];
end
