function A = linear_A_matrix(in1)
%linear_A_matrix
%    A = linear_A_matrix(IN1)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/23 13:04:31

G = in1(8,:);
Iw = in1(6,:);
Jp = in1(9,:);
Ke = in1(13,:);
Kt = in1(12,:);
La = in1(15,:);
M = in1(1,:);
Ra = in1(14,:);
btheta = in1(11,:);
bx = in1(10,:);
g = in1(3,:);
l = in1(4,:);
m = in1(2,:);
n = in1(7,:);
r = in1(5,:);
t2 = Iw.*n;
t3 = l.^2;
t4 = r.^2;
t6 = 1.0./La;
t5 = Jp.*t2;
t7 = M.*t4;
t8 = m.*t3;
t9 = m.*t4;
t10 = Jp.*t7;
t11 = Jp.*t9;
t12 = Jp+t8;
t13 = t2.*t8;
t14 = t7.*t8;
t15 = t2+t7+t9;
t16 = t5+t10+t11+t13+t14;
t17 = 1.0./t16;
A = reshape([0.0,0.0,0.0,0.0,0.0,1.0,-bx.*t4.*t12.*t17,0.0,bx.*l.*t9.*t17,-(G.*Ke.*t6)./r,0.0,-g.*t8.*t9.*t17,0.0,g.*l.*m.*t15.*t17,0.0,0.0,btheta.*l.*t9.*t17,1.0,-btheta.*t15.*t17,0.0,0.0,G.*Kt.*r.*t12.*t17,0.0,-G.*Kt.*l.*m.*r.*t17,-Ra.*t6],[5,5]);
end
