function dXdt = nonlinear_dynamics(in1,V,in3)
%NONLINEAR_DYNAMICS
%    dXdt = NONLINEAR_DYNAMICS(IN1,V,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/23 13:04:30

G = in3(8,:);
Iw = in3(6,:);
Jp = in3(9,:);
Ke = in3(13,:);
Kt = in3(12,:);
La = in3(15,:);
M = in3(1,:);
Ra = in3(14,:);
btheta = in3(11,:);
bx = in3(10,:);
g = in3(3,:);
i = in1(5,:);
l = in3(4,:);
m = in3(2,:);
n = in3(7,:);
phi = in1(3,:);
phi_dot = in1(4,:);
r = in3(5,:);
x_dot = in1(2,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = l.^2;
t5 = m.^2;
t6 = phi_dot.^2;
t7 = r.^2;
t9 = Iw.*Jp.*n;
t8 = t2.^2;
t10 = Jp.*M.*t7;
t11 = Jp.*m.*t7;
t12 = Iw.*m.*n.*t4;
t13 = M.*m.*t4.*t7;
t14 = t4.*t5.*t7;
t15 = t8.*t14;
t16 = -t15;
t17 = t9+t10+t11+t12+t13+t14+t16;
t18 = 1.0./t17;
dXdt = [x_dot;r.*t18.*(G.*Jp.*Kt.*i-Jp.*bx.*r.*x_dot+G.*Kt.*i.*m.*t4-bx.*m.*r.*t4.*x_dot+l.^3.*r.*t3.*t5.*t6-g.*r.*t2.*t3.*t4.*t5+Jp.*l.*m.*r.*t3.*t6+btheta.*l.*m.*phi_dot.*r.*t2);phi_dot;-t18.*(btheta.*m.*phi_dot.*t7+t2.*t3.*t6.*t14+Iw.*btheta.*n.*phi_dot+M.*btheta.*phi_dot.*t7-g.*l.*t3.*t5.*t7-Iw.*g.*l.*m.*n.*t3-M.*g.*l.*m.*t3.*t7-bx.*l.*m.*t2.*t7.*x_dot+G.*Kt.*i.*l.*m.*r.*t2);-(-V+Ra.*i+(G.*Ke.*x_dot)./r)./La];
end
