function [nonlinear_A,nonlinear_B] = nonlinear_A_B_matrix(in1,V,in3)
%nonlinear_A_B_matrix
%    [nonlinear_A,nonlinear_B] = nonlinear_A_B_matrix(IN1,V,IN3)

%    This function was generated by the Symbolic Math Toolbox version 25.1.
%    2025/06/27 10:08:35

G = in3(7,:);
Iw = in3(6,:);
Jp = in3(8,:);
Ke = in3(12,:);
Kt = in3(11,:);
La = in3(14,:);
M = in3(1,:);
Ra = in3(13,:);
btheta = in3(10,:);
bx = in3(9,:);
g = in3(3,:);
i = in1(5,:);
l = in3(4,:);
m = in3(2,:);
phi = in1(3,:);
phi_dot = in1(4,:);
r = in3(5,:);
x_dot = in1(2,:);
t2 = cos(phi);
t3 = sin(phi);
t4 = l.^2;
t5 = l.^3;
t6 = m.^2;
t7 = phi_dot.^2;
t8 = r.^2;
t11 = 1.0./La;
t12 = Iw.*Jp.*2.0;
t9 = t2.^2;
t10 = t3.^2;
t13 = Jp.*M.*t8;
t14 = Jp.*m.*t8;
t15 = Iw.*m.*t4.*2.0;
t16 = M.*m.*t4.*t8;
t17 = t4.*t6.*t8;
t18 = t9.*t17;
t19 = -t18;
t20 = t12+t13+t14+t15+t16+t17+t19;
t21 = 1.0./t20;
t22 = t21.^2;
mt1 = [0.0,0.0,0.0,0.0,0.0,1.0,-r.*t21.*(Jp.*bx.*r+bx.*m.*r.*t4),0.0,bx.*l.*m.*t2.*t8.*t21,-(G.*Ke.*t11)./r,0.0,r.*t21.*(-g.*r.*t4.*t6.*t9+g.*r.*t4.*t6.*t10+r.*t2.*t5.*t6.*t7+Jp.*l.*m.*r.*t2.*t7-btheta.*l.*m.*phi_dot.*r.*t3)-r.^3.*t2.*t3.*t4.*t6.*t22.*(G.*Jp.*Kt.*i.*2.0-Jp.*bx.*r.*x_dot+G.*Kt.*i.*m.*t4.*2.0-bx.*m.*r.*t4.*x_dot+r.*t3.*t5.*t6.*t7-g.*r.*t2.*t3.*t4.*t6+Jp.*l.*m.*r.*t3.*t7+btheta.*l.*m.*phi_dot.*r.*t2).*2.0,0.0];
mt2 = [t21.*(t7.*t19+t7.*t10.*t17+Iw.*g.*l.*m.*t2.*2.0+g.*l.*t2.*t6.*t8+M.*g.*l.*m.*t2.*t8-bx.*l.*m.*t3.*t8.*x_dot+G.*Kt.*i.*l.*m.*r.*t3.*2.0)+t2.*t3.*t17.*t22.*(Iw.*btheta.*phi_dot.*2.0+btheta.*m.*phi_dot.*t8+t2.*t3.*t7.*t17+M.*btheta.*phi_dot.*t8-Iw.*g.*l.*m.*t3.*2.0-g.*l.*t3.*t6.*t8-M.*g.*l.*m.*t3.*t8-bx.*l.*m.*t2.*t8.*x_dot+G.*Kt.*i.*l.*m.*r.*t2.*2.0).*2.0,0.0,0.0,r.*t21.*(btheta.*l.*m.*r.*t2+phi_dot.*r.*t3.*t5.*t6.*2.0+Jp.*l.*m.*phi_dot.*r.*t3.*2.0),1.0,-t21.*(Iw.*btheta.*2.0+M.*btheta.*t8+btheta.*m.*t8+phi_dot.*t2.*t3.*t17.*2.0),0.0,0.0,r.*t21.*(G.*Jp.*Kt.*2.0+G.*Kt.*m.*t4.*2.0),0.0,G.*Kt.*l.*m.*r.*t2.*t21.*-2.0];
mt3 = [-Ra.*t11];
nonlinear_A = reshape([mt1,mt2,mt3],5,5);
if nargout > 1
    nonlinear_B = [0.0;0.0;0.0;0.0;t11];
end
end
